# Generated by Django 3.2.19 on 2023-05-06 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
