# Generated by Django 3.2.19 on 2023-05-07 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_examsubmission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExamSubmission',
        ),
    ]
