# Generated by Django 3.2.19 on 2023-05-07 10:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_delete_examsubmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('submission_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('score', models.IntegerField()),
            ],
        ),
    ]
